Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,38 +1,67 @@
-name: Publish Static Web App to Azure Blob Storage
+name: Atedu Frontend CI/CD
 
-on: push
+on:
+  push:
+    branches:
+      - atedu-dev
+  pull_request:
+    types: [opened, synchronize, reopened, closed]
+    brances:
+      - atedu-dev
 
 jobs:
-  build_and_publish:
+  build_and_deploy_job:
+    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
     runs-on: ubuntu-latest
-
+    env:
+      CI: false
     steps:
-    - name: Checkout the repo
-      uses: actions/checkout@v1
+      #Checkout Code
+      - name: Checkout Code
+        uses: actions/checkout@v2
 
-    - name: Login to Azure
-      uses: Azure/login@v1
-      with:
-        creds: ${{ secrets.AZURE_CREDENTIALS }}
+      #Setup Node
+      - name: Use Node.js 12.x
+        uses: actions/setup-node@v1
+        with:
+          node-version: 12.x
 
-    - name: Install npm packages
-      shell: bash
-      run: |
-        cd NewTest
-        npm install
-    - name: Build app
-      shell: bash
-      run: |
-        cd NewTest
-        npm run build
-    - name: Test app
-      shell: bash
-      run: |
-        cd NewTest
-        npm run test:unit
-    - name: Publish app
-      uses: Azure/cli@v1.0.0
-      with:
-        azcliversion: latest
-        inlineScript: |
-          az storage blob upload-batch -s $NewTest/build -d \$web --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }}
+      #Install, Build and Test if present
+      - name: npm install, build and test
+        run: |
+          npm install
+          npm run build --if present
+      #   npm run test --if present
+      #Download Build files
+
+      #Login to Azure
+      - name: Azure Login
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+      #Cleanup Blob Container
+      - name: Azure CLI Script
+        uses: azure/CLI@v1
+        with:
+          azcliversion: 2.0.72
+          inlineScript: |
+            az storage blob delete-batch --account-name devatedu --source $web
+      #Upload Files
+      - name: Azure CLI Script
+        uses: azure/CLI@v1
+        with:
+          azcliversion: 2.0.72
+          inlineScript: |
+            az storage blob upload-batch --account-name devatedu -d '$web' -s .
+      #Purge CND
+      - name: Azure CLI Script
+        uses: azure/CLI@v1
+        with:
+          azcliversion: 2.0.72
+          inlineScript: |
+            az cdn endpoint purge --content-path "/*" --profile-name devatedu --name devatedu --resource-group atedu-dev
+      #Azure Logout
+      - name: Logout
+        run: |
+          az logout
